[package]
name = "piramid-inference"
description = "Model execution and retrieval fusion."
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
piramid-core.workspace = true
piramid-gpu.workspace = true

[dev-dependencies]

[features]
default = []
inference-candle = []

[lints]
workspace = true
