[package]
name = "piramid-search"
description = "Query execution: filtering, scoring, ranking."
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
piramid-core.workspace = true
piramid-compute.workspace = true
piramid-storage.workspace = true
piramid-index.workspace = true
rayon.workspace = true
uuid.workspace = true

[dev-dependencies]

[lints]
workspace = true
