//! Diagnostic bundle generation: version, platform, config, features, and collection/WAL state.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use piramid::config::Config;
use piramid::state::AppState;

/// Substrings matched case-insensitively against env var names to redact their values.
const SECRET_MARKERS: &[&str] = &[
    "KEY",
    "TOKEN",
    "SECRET",
    "PASSWORD",
    "DSN",
    "CREDENTIAL",
    "AUTH",
];

/// Environment variables worth reporting, beyond the resolved config.
const REPORTED_PREFIXES: &[&str] = &[
    "PIRAMID__",
    "PIRAMID_",
    "EMBEDDING_",
    "OPENAI_",
    "LOG_",
    "CACHE_",
    "INDEX_",
    "SEARCH_",
    "WAL_",
    "MEMORY_",
    "QUANTIZATION_",
    "HARDWARE_",
    "LIMIT_",
    "DISK_",
    "EXECUTION_",
    "RUST_LOG",
    "DATA_DIR",
    "PORT",
    "CONFIG_FILE",
    "NUM_THREADS",
    "PARALLEL_SEARCH",
];

/// Clone the config with the embedding API key replaced by a redaction marker.
fn redacted(config: &Config) -> Config {
    let mut config = config.clone();
    if let Some(embedding) = config.startup.embedding.as_mut() {
        if embedding.api_key.is_some() {
            embedding.api_key = Some("<redacted>".to_string());
        }
    }
    config
}

fn is_secret(name: &str) -> bool {
    let upper = name.to_ascii_uppercase();
    SECRET_MARKERS.iter().any(|marker| upper.contains(marker))
}

pub fn render(config: &Config, state: &Arc<AppState>) -> String {
    let mut out = String::new();

    let _ = writeln!(out, "# Piramid support bundle");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Generated by `piramid support-bundle`. Review before sharing; values that look like\n\
         credentials are redacted, but check anyway."
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "## Version");
    let _ = writeln!(out);
    let _ = writeln!(out, "piramid   {}", env!("CARGO_PKG_VERSION"));
    let _ = writeln!(out, "target    {}", std::env::consts::ARCH);
    let _ = writeln!(out, "os        {}", std::env::consts::OS);
    let _ = writeln!(out);

    let _ = writeln!(out, "## Build features");
    let _ = writeln!(out);
    for (name, enabled) in [
        ("gpu-cuda", cfg!(feature = "gpu-cuda")),
        ("inference-candle", cfg!(feature = "inference-candle")),
        ("otel", cfg!(feature = "otel")),
    ] {
        let _ = writeln!(out, "{name:<18} {}", if enabled { "on" } else { "off" });
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## Compute strategies");
    let _ = writeln!(out);
    for strategy in piramid::compute::strategies::all() {
        let _ = writeln!(
            out,
            "{:<10} {}",
            strategy.name(),
            if strategy.is_available() {
                "available"
            } else {
                "unavailable"
            }
        );
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## Runtime");
    let _ = writeln!(out);
    let _ = writeln!(out, "bind                {}", config.startup.bind);
    let _ = writeln!(out, "data_dir            {}", config.startup.data_dir);
    let _ = writeln!(
        out,
        "slow_query_ms       {}",
        config.startup.logging.slow_query_ms
    );
    let _ = writeln!(
        out,
        "embedding_provider  {}",
        config.startup.embedding.as_ref().map_or_else(
            || "none".to_string(),
            |e| format!("{} ({})", e.provider, e.model)
        )
    );
    let _ = writeln!(
        out,
        "disk_min_free       {}",
        config
            .startup
            .disk
            .min_free_bytes
            .map_or_else(|| "unset".to_string(), |b| b.to_string())
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "## Environment");
    let _ = writeln!(out);
    let mut vars: Vec<(String, String)> = std::env::vars()
        .filter(|(name, _)| REPORTED_PREFIXES.iter().any(|p| name.starts_with(p)))
        .map(|(name, value)| {
            let value = if is_secret(&name) {
                format!("<redacted, {} chars>", value.len())
            } else {
                value
            };
            (name, value)
        })
        .collect();
    vars.sort();
    if vars.is_empty() {
        let _ = writeln!(out, "(none set; running on defaults)");
    }
    for (name, value) in vars {
        let _ = writeln!(out, "{name}={value}");
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## Collections");
    let _ = writeln!(out);
    match piramid::services::admin::metrics(state) {
        Ok(metrics) => {
            let _ = writeln!(out, "collections   {}", metrics.total_collections);
            let _ = writeln!(out, "vectors       {}", metrics.total_vectors);
            let _ = writeln!(out);
            for c in &metrics.collections {
                let _ = writeln!(out, "### {}", c.name);
                let _ = writeln!(out, "vectors        {}", c.vector_count);
                let _ = writeln!(out, "index          {}", c.index_type);
                let _ = writeln!(out, "memory_bytes   {}", c.memory_usage_bytes);
                if let Some(v) = c.insert_latency_ms {
                    let _ = writeln!(out, "insert_ms      {v:.3}");
                }
                if let Some(v) = c.search_latency_ms {
                    let _ = writeln!(out, "search_ms      {v:.3}");
                }
                if let Some(v) = c.hnsw_ef_search {
                    let _ = writeln!(out, "hnsw_ef_search {v}");
                }
                if let Some(v) = c.ivf_nprobe {
                    let _ = writeln!(out, "ivf_nprobe     {v}");
                }
                let _ = writeln!(out);
            }
            let _ = writeln!(out, "## Write-ahead log");
            let _ = writeln!(out);
            for w in &metrics.wal_stats {
                let _ = writeln!(
                    out,
                    "{:<20} size={} checkpoint_age_secs={}",
                    w.collection,
                    w.wal_size_bytes
                        .map_or_else(|| "?".into(), |b| b.to_string()),
                    w.checkpoint_age_secs
                        .map_or_else(|| "?".into(), |a| a.to_string()),
                );
            }
        }
        Err(error) => {
            let _ = writeln!(out, "failed to collect metrics: {error}");
        }
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## Resolved configuration");
    let _ = writeln!(out);
    match yaml_serde::to_string(&redacted(config)) {
        Ok(yaml) => {
            let _ = writeln!(out, "```yaml");
            let _ = write!(out, "{yaml}");
            let _ = writeln!(out, "```");
        }
        Err(error) => {
            let _ = writeln!(out, "failed to serialize configuration: {error}");
        }
    }

    out
}

/// Write the bundle to path, defaulting to piramid-support-bundle.md in the working directory.
pub fn write(
    config: &Config,
    state: &Arc<AppState>,
    path: Option<PathBuf>,
) -> std::io::Result<PathBuf> {
    let path = path.unwrap_or_else(|| Path::new("piramid-support-bundle.md").to_path_buf());
    fs::write(&path, render(config, state))?;
    Ok(path)
}
