//! Diagnostic bundle generation: build, configuration and on-disk state of a serve deployment.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use serde::Serialize;

use crate::config::{Config, EmbeddingProvider, HardwareConfig, InferenceConfig};
use crate::error::{PiramidError, StorageError};
use crate::storage::SidecarManager;

/// Substrings matched case-insensitively against env var names to redact their values.
const SECRET_MARKERS: &[&str] = &[
    "KEY",
    "TOKEN",
    "SECRET",
    "PASSWORD",
    "DSN",
    "CREDENTIAL",
    "AUTH",
];

/// Environment variables Piramid reads, by prefix, reported beside the resolved config.
const REPORTED_PREFIXES: &[&str] = &["PIRAMID_", "CONFIG_FILE", "OPENAI_API_KEY"];

/// Whether this build carries the inference-candle feature.
const INFERENCE_CANDLE: bool = cfg!(feature = "inference-candle");

/// Whether this build carries the gpu-cuda feature.
const GPU_CUDA: bool = cfg!(feature = "gpu-cuda");

fn is_secret(name: &str) -> bool {
    let upper = name.to_ascii_uppercase();
    SECRET_MARKERS.iter().any(|marker| upper.contains(marker))
}

/// The inputs a support bundle is rendered from.
pub struct Bundle<'a> {
    /// The resolved configuration.
    pub config: &'a Config,
    /// The config file named on the command line, if any.
    pub config_file: Option<&'a Path>,
}

/// Render the bundle as markdown.
pub fn render(bundle: &Bundle<'_>) -> String {
    let mut out = String::new();

    let _ = writeln!(out, "# Piramid support bundle");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Generated by piramid support-bundle. It is read from the binary, the configuration and\n\
         the data directory without opening a collection or writing to it, so it is safe to run\n\
         beside a running server. Values that look like credentials are\n\
         redacted; review it before sharing."
    );
    let _ = writeln!(out);

    version(&mut out);
    build_features(&mut out);
    compute_strategies(&mut out);
    runtime(&mut out, bundle);
    hardware(&mut out, &bundle.config.startup.hardware);
    inference(
        &mut out,
        &bundle.config.runtime.inference,
        &bundle.config.startup.hardware,
    );
    embedding(&mut out, bundle.config);
    environment(&mut out);
    collections(&mut out, &bundle.config.startup.data_dir);
    resolved_configuration(&mut out, bundle.config);

    out
}

/// Write the rendered bundle to path.
pub fn write(bundle: &Bundle<'_>, path: &Path) -> std::io::Result<()> {
    fs::write(path, render(bundle))
}

fn version(out: &mut String) {
    let _ = writeln!(out, "## Version");
    let _ = writeln!(out);
    let _ = writeln!(out, "piramid   {}", env!("CARGO_PKG_VERSION"));
    let _ = writeln!(out, "target    {}", std::env::consts::ARCH);
    let _ = writeln!(out, "os        {}", std::env::consts::OS);
    let _ = writeln!(out);
}

fn build_features(out: &mut String) {
    let _ = writeln!(out, "## Build features");
    let _ = writeln!(out);
    for (name, enabled) in [
        ("gpu-cuda", GPU_CUDA),
        ("inference-candle", INFERENCE_CANDLE),
        ("otel", cfg!(feature = "otel")),
    ] {
        let _ = writeln!(out, "{name:<18} {}", on_off(enabled));
    }
    let _ = writeln!(out);
}

fn compute_strategies(out: &mut String) {
    let _ = writeln!(out, "## Compute strategies");
    let _ = writeln!(out);
    for strategy in crate::compute::strategies::all() {
        let _ = writeln!(
            out,
            "{:<10} {}",
            strategy.name(),
            if strategy.is_available() {
                "available"
            } else {
                "unavailable"
            }
        );
    }
    let _ = writeln!(out);
}

fn runtime(out: &mut String, bundle: &Bundle<'_>) {
    let startup = &bundle.config.startup;
    let _ = writeln!(out, "## Runtime");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "config_file         {}",
        bundle
            .config_file
            .map_or_else(|| "none".to_string(), |p| p.display().to_string())
    );
    let _ = writeln!(out, "bind                {}", startup.bind);
    let _ = writeln!(out, "data_dir            {}", startup.data_dir);
    let _ = writeln!(out, "threads             {}", startup.num_threads());
    let _ = writeln!(
        out,
        "execution           {}",
        bundle.config.runtime.execution.as_str()
    );
    let _ = writeln!(out, "slow_query_ms       {}", startup.logging.slow_query_ms);
    let _ = writeln!(
        out,
        "disk_min_free       {}",
        startup
            .disk
            .min_free_bytes
            .map_or_else(|| "unset".to_string(), |b| b.to_string())
    );
    let _ = writeln!(out);
}

fn hardware(out: &mut String, hardware: &HardwareConfig) {
    let gpu = &hardware.gpu;
    let vram = &hardware.vram;
    let _ = writeln!(out, "## Hardware");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "profile                  {}",
        hardware.profile.as_str()
    );
    let _ = writeln!(
        out,
        "memory_budget_bytes      {}",
        hardware
            .memory_budget()
            .map_or_else(|| "unbounded".to_string(), |b| b.to_string())
    );
    let _ = writeln!(
        out,
        "gpu_memory_budget_bytes  {}",
        hardware
            .gpu_memory_budget_bytes
            .map_or_else(|| "whole device".to_string(), |b| b.to_string())
    );
    let _ = writeln!(out, "gpu.device_ordinal       {}", gpu.device_ordinal);
    let _ = writeln!(out, "gpu.reserve_bytes        {}", gpu.reserve_bytes);
    let _ = writeln!(out, "gpu.streams              {}", gpu.streams);
    let _ = writeln!(out, "gpu.distance_block_size  {}", gpu.distance_block_size);
    if vram.enabled {
        let _ = writeln!(
            out,
            "vram split               weights {} kv {} vectors {}",
            vram.weights_ratio, vram.kv_ratio, vram.vectors_ratio
        );
    } else {
        let _ = writeln!(
            out,
            "vram split               off, every pool draws from one budget"
        );
    }
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "No device was opened. GPU memory, utilisation and the budget in use are reported by a\n\
         running server at GET /api/metrics."
    );
    let _ = writeln!(out);
}

fn inference(out: &mut String, inference: &InferenceConfig, hardware: &HardwareConfig) {
    let batching = &inference.batching;
    let kv = &inference.kv_cache;
    let _ = writeln!(out, "## Inference");
    let _ = writeln!(out);
    let _ = writeln!(out, "enabled                  {}", inference.enabled);
    let _ = writeln!(
        out,
        "model_path               {}",
        inference
            .model_path
            .as_deref()
            .map_or_else(|| "unset".to_string(), path_presence)
    );
    let _ = writeln!(
        out,
        "model_name               {}",
        inference
            .model_name
            .as_deref()
            .unwrap_or("unset, the model_path directory name")
    );
    let _ = writeln!(
        out,
        "tokenizer_path           {}",
        inference.tokenizer_path.as_deref().map_or_else(
            || "unset, the model_path directory".to_string(),
            path_presence
        )
    );
    let _ = writeln!(
        out,
        "architecture             {}",
        inference
            .architecture
            .as_deref()
            .unwrap_or("unset, read from the checkpoint")
    );
    let _ = writeln!(
        out,
        "device                   {}{}",
        inference.resolved_device(hardware),
        if inference.device.is_none() {
            " (unset, from the hardware profile)"
        } else {
            ""
        }
    );
    let _ = writeln!(
        out,
        "dtype                    {}",
        wire_name(&inference.dtype)
    );
    let _ = writeln!(
        out,
        "max_sequence_length      {}",
        inference.max_sequence_length
    );
    let _ = writeln!(out, "warmup                   {}", inference.warmup);
    let _ = writeln!(
        out,
        "batching                 continuous {}, chunked_prefill {}",
        on_off(batching.continuous),
        on_off(batching.chunked_prefill)
    );
    let _ = writeln!(out, "max_batch_size           {}", batching.max_batch_size);
    let _ = writeln!(out, "max_queue_depth          {}", batching.max_queue_depth);
    let _ = writeln!(
        out,
        "max_batched_tokens       {}",
        batching.max_batched_tokens
    );
    let _ = writeln!(
        out,
        "queue_timeout_ms         {}",
        batching
            .queue_timeout_ms
            .map_or_else(|| "none, waits forever".to_string(), |ms| ms.to_string())
    );
    let _ = writeln!(
        out,
        "kv_cache.max_bytes       {}",
        kv.max_bytes
            .map_or_else(|| "unset".to_string(), |b| b.to_string())
    );
    let _ = writeln!(out, "kv_cache.device_fraction {}", kv.device_fraction);
    let _ = writeln!(out, "kv_cache.page_size       {}", kv.page_size);
    let _ = writeln!(out, "kv_cache.dtype           {}", wire_name(&kv.dtype));
    let _ = writeln!(out, "kv_cache.prefix_sharing  {}", kv.prefix_sharing);
    let _ = writeln!(
        out,
        "kv_cache.preemption      {}",
        wire_name(&kv.preemption)
    );
    let _ = writeln!(out);
    if inference.enabled && !INFERENCE_CANDLE {
        let _ = writeln!(
            out,
            "Inference is enabled and this build has no inference-candle feature, so serve refuses to start."
        );
    }
    let _ = writeln!(
        out,
        "No model was loaded. The loaded model, its device, KV pages and generation counters are\n\
         reported by a running server at GET /api/model and GET /api/metrics."
    );
    let _ = writeln!(out);
}

fn embedding(out: &mut String, config: &Config) {
    let _ = writeln!(out, "## Embedding");
    let _ = writeln!(out);
    let Some(embedding) = &config.startup.embedding else {
        let _ = writeln!(
            out,
            "No provider is configured. The server does not embed text."
        );
        let _ = writeln!(out);
        return;
    };
    let _ = writeln!(out, "provider   {}", embedding.provider);
    let _ = writeln!(out, "model      {}", embedding.model);
    match embedding.provider {
        EmbeddingProvider::Piramid => match embedding.piramid_options() {
            Ok(options) => {
                let _ = writeln!(out, "device     {}", options.device);
                let _ = writeln!(out, "dtype      {}", wire_name(&options.dtype));
                let _ = writeln!(out, "max_tokens {}", options.max_tokens);
            }
            Err(error) => {
                let _ = writeln!(out, "options    {error}");
            }
        },
        EmbeddingProvider::OpenAI | EmbeddingProvider::Ollama => {
            let _ = writeln!(
                out,
                "base_url   {}",
                embedding
                    .base_url
                    .as_deref()
                    .unwrap_or("unset, the provider default")
            );
            let _ = writeln!(
                out,
                "timeout    {}",
                embedding
                    .timeout
                    .map_or_else(|| "unset".to_string(), |secs| format!("{secs}s"))
            );
        }
    }
    let _ = writeln!(
        out,
        "cache      {}",
        if embedding.cache.enabled {
            format!("on, {} entries", embedding.cache.entries)
        } else {
            "off".to_string()
        }
    );
    let _ = writeln!(out);
    if embedding.provider == EmbeddingProvider::Piramid && !INFERENCE_CANDLE {
        let _ = writeln!(
            out,
            "The piramid provider needs the inference-candle feature, which this build lacks, so serve refuses to start."
        );
        let _ = writeln!(out);
    }
}

fn environment(out: &mut String) {
    let _ = writeln!(out, "## Environment");
    let _ = writeln!(out);
    let mut vars: Vec<(String, String)> = std::env::vars()
        .filter(|(name, _)| REPORTED_PREFIXES.iter().any(|p| name.starts_with(p)))
        .map(|(name, value)| {
            let value = if is_secret(&name) {
                format!("<redacted, {} chars>", value.len())
            } else {
                value
            };
            (name, value)
        })
        .collect();
    vars.sort();
    if vars.is_empty() {
        let _ = writeln!(out, "(none set)");
    }
    for (name, value) in vars {
        let _ = writeln!(out, "{name}={value}");
    }
    let _ = writeln!(out);
}

fn collections(out: &mut String, data_dir: &str) {
    let _ = writeln!(out, "## Collections");
    let _ = writeln!(out);
    let names = match crate::collection_names(data_dir) {
        Ok(names) => names,
        Err(error) => {
            let _ = writeln!(out, "failed to list {data_dir}: {error}");
            let _ = writeln!(out);
            return;
        }
    };
    let _ = writeln!(out, "collections   {}", names.len());
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Each collection is read from its manifest and file sizes, without opening it. Document\n\
         counts are as of the last checkpoint; writes still in the write-ahead log are not counted."
    );
    let _ = writeln!(out);
    for name in &names {
        collection(out, data_dir, name);
    }
    let _ = writeln!(
        out,
        "The time of the last checkpoint is kept in memory. A running server reports it at\n\
         GET /api/metrics."
    );
    let _ = writeln!(out);
}

fn collection(out: &mut String, data_dir: &str, name: &str) {
    let base = crate::record_path(data_dir, name);
    let sidecars = SidecarManager::at(&base);
    let _ = writeln!(out, "### {name}");
    match sidecars.load_manifest() {
        Ok(Some(manifest)) => {
            let _ = writeln!(out, "documents       {}", manifest.vector_count);
            let _ = writeln!(
                out,
                "dimension       {}",
                manifest
                    .dimensions
                    .map_or_else(|| "none, no vector stored".to_string(), |d| d.to_string())
            );
            let _ = writeln!(out, "metric          {}", manifest.metric.as_str());
            let _ = writeln!(out, "schema_version  {}", manifest.schema_version);
        }
        Ok(None) => {
            let _ = writeln!(out, "manifest        missing");
        }
        Err(PiramidError::Storage(StorageError::LegacyManifest { .. })) => {
            let _ = writeln!(
                out,
                "schema_version  1, written by Piramid 0.2, must be re-ingested"
            );
        }
        Err(error) => {
            let _ = writeln!(out, "manifest        unreadable: {error}");
        }
    }
    for (label, path) in [
        ("record_bytes", base.clone()),
        ("wal_bytes", sidecars.wal_path()),
        ("offsets_bytes", sidecars.offsets_path()),
    ] {
        let _ = writeln!(out, "{label:<15} {}", file_size(&path));
    }
    let _ = writeln!(out);
}

/// The byte size of the file at path, or why it has none.
fn file_size(path: &str) -> String {
    match fs::metadata(path) {
        Ok(meta) => meta.len().to_string(),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => "none".to_string(),
        Err(error) => format!("unreadable: {error}"),
    }
}

fn resolved_configuration(out: &mut String, config: &Config) {
    let _ = writeln!(out, "## Resolved configuration");
    let _ = writeln!(out);
    match yaml_serde::to_string(config) {
        Ok(yaml) => {
            let _ = writeln!(out, "```yaml");
            let _ = write!(out, "{yaml}");
            let _ = writeln!(out, "```");
        }
        Err(error) => {
            let _ = writeln!(out, "failed to serialize configuration: {error}");
        }
    }
}

/// On or off, for a switch.
fn on_off(enabled: bool) -> &'static str {
    if enabled {
        "on"
    } else {
        "off"
    }
}

/// A path followed by whether it exists on this machine.
fn path_presence(path: &str) -> String {
    if Path::new(path).exists() {
        path.to_string()
    } else {
        format!("{path} (missing on this machine)")
    }
}

/// The name a configuration file uses for a setting value.
fn wire_name<T: Serialize>(value: &T) -> String {
    match serde_json::to_value(value) {
        Ok(serde_json::Value::String(name)) => name,
        Ok(other) => other.to_string(),
        Err(error) => format!("unrepresentable: {error}"),
    }
}
