//! Diagnostic bundle generation.
//!
//! Piramid is self-hosted: the operator runs it on their hardware with their data, and no
//! telemetry reaches this project unless they deliberately configure an exporter of their own.
//! That is the correct default for a database, and it means a bug report is the only channel
//! through which a maintainer learns anything.
//!
//! This command exists to make that channel carry enough signal. It writes everything a
//! maintainer usually has to ask for over three round-trips — version, platform, resolved
//! configuration, enabled features, collection and WAL state — into one file the operator can
//! read, check, and attach.
//!
//! # What it must never do
//!
//! Emit a secret. The bundle is written to be pasted into a public issue tracker, so every value
//! that could be a credential is redacted, and the operator is told what was collected so they
//! can verify before sharing.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use piramid::config::loader::RuntimeConfig;
use piramid::runtime::AppState;

/// Environment variables whose values are never included.
///
/// Matched case-insensitively as substrings, so `OPENAI_API_KEY` and `PIRAMID_SENTRY_DSN` are both
/// caught. Prefer over-redacting: a missing value costs a follow-up question, a leaked one costs a
/// credential rotation.
const SECRET_MARKERS: &[&str] = &[
    "KEY",
    "TOKEN",
    "SECRET",
    "PASSWORD",
    "DSN",
    "CREDENTIAL",
    "AUTH",
];

/// Environment variables worth reporting, beyond the resolved config.
/// Credential variables are included too, as a redacted placeholder: whether a key is *set* is
/// diagnostic ("the provider is configured but calls fail"), while its value never is.
const REPORTED_PREFIXES: &[&str] = &[
    "PIRAMID_",
    "EMBEDDING_",
    "OPENAI_",
    "LOG_",
    "CACHE_",
    "INDEX_",
    "SEARCH_",
    "WAL_",
    "MEMORY_",
    "QUANTIZATION_",
    "HARDWARE_",
    "LIMIT_",
    "DISK_",
    "EXECUTION_",
    "RUST_LOG",
    "DATA_DIR",
    "PORT",
    "CONFIG_FILE",
    "NUM_THREADS",
    "PARALLEL_SEARCH",
];

/// Whether a variable name looks like it holds a credential.
fn is_secret(name: &str) -> bool {
    let upper = name.to_ascii_uppercase();
    SECRET_MARKERS.iter().any(|marker| upper.contains(marker))
}

/// Build the bundle text.
pub fn render(config: &RuntimeConfig, state: &Arc<AppState>) -> String {
    let mut out = String::new();

    let _ = writeln!(out, "# Piramid support bundle");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Generated by `piramid support-bundle`. Review before sharing; values that look like\n\
         credentials are redacted, but check anyway."
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "## Version");
    let _ = writeln!(out);
    let _ = writeln!(out, "piramid   {}", env!("CARGO_PKG_VERSION"));
    let _ = writeln!(out, "target    {}", std::env::consts::ARCH);
    let _ = writeln!(out, "os        {}", std::env::consts::OS);
    let _ = writeln!(out);

    let _ = writeln!(out, "## Build features");
    let _ = writeln!(out);
    for (name, enabled) in [
        ("gpu-cuda", cfg!(feature = "gpu-cuda")),
        ("inference-candle", cfg!(feature = "inference-candle")),
        ("otel", cfg!(feature = "otel")),
    ] {
        let _ = writeln!(out, "{name:<18} {}", if enabled { "on" } else { "off" });
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## Compute backends");
    let _ = writeln!(out);
    for backend in piramid::compute::backends::all() {
        let _ = writeln!(
            out,
            "{:<10} {}",
            backend.name(),
            if backend.is_available() {
                "available"
            } else {
                "unavailable"
            }
        );
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## Runtime");
    let _ = writeln!(out);
    let _ = writeln!(out, "port                {}", config.port);
    let _ = writeln!(out, "data_dir            {}", config.data_dir);
    let _ = writeln!(out, "slow_query_ms       {}", config.slow_query_ms);
    let _ = writeln!(
        out,
        "embedding_provider  {}",
        config
            .embedding
            .as_ref()
            .map(|e| format!("{} ({})", e.provider, e.model))
            .unwrap_or_else(|| "none".to_string())
    );
    let _ = writeln!(
        out,
        "disk_min_free       {}",
        config
            .disk_min_free_bytes
            .map(|b| b.to_string())
            .unwrap_or_else(|| "unset".to_string())
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "## Environment");
    let _ = writeln!(out);
    let mut vars: Vec<(String, String)> = std::env::vars()
        .filter(|(name, _)| REPORTED_PREFIXES.iter().any(|p| name.starts_with(p)))
        .map(|(name, value)| {
            let value = if is_secret(&name) {
                format!("<redacted, {} chars>", value.len())
            } else {
                value
            };
            (name, value)
        })
        .collect();
    vars.sort();
    if vars.is_empty() {
        let _ = writeln!(out, "(none set; running on defaults)");
    }
    for (name, value) in vars {
        let _ = writeln!(out, "{name}={value}");
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## Collections");
    let _ = writeln!(out);
    match piramid::services::admin::metrics(state) {
        Ok(metrics) => {
            let _ = writeln!(out, "collections   {}", metrics.total_collections);
            let _ = writeln!(out, "vectors       {}", metrics.total_vectors);
            let _ = writeln!(out);
            for c in &metrics.collections {
                let _ = writeln!(out, "### {}", c.name);
                let _ = writeln!(out, "vectors        {}", c.vector_count);
                let _ = writeln!(out, "index          {}", c.index_type);
                let _ = writeln!(out, "memory_bytes   {}", c.memory_usage_bytes);
                if let Some(v) = c.insert_latency_ms {
                    let _ = writeln!(out, "insert_ms      {v:.3}");
                }
                if let Some(v) = c.search_latency_ms {
                    let _ = writeln!(out, "search_ms      {v:.3}");
                }
                if let Some(v) = c.hnsw_ef_search {
                    let _ = writeln!(out, "hnsw_ef_search {v}");
                }
                if let Some(v) = c.ivf_nprobe {
                    let _ = writeln!(out, "ivf_nprobe     {v}");
                }
                let _ = writeln!(out);
            }
            let _ = writeln!(out, "## Write-ahead log");
            let _ = writeln!(out);
            for w in &metrics.wal_stats {
                let _ = writeln!(
                    out,
                    "{:<20} size={} checkpoint_age_secs={}",
                    w.collection,
                    w.wal_size_bytes
                        .map(|b| b.to_string())
                        .unwrap_or_else(|| "?".into()),
                    w.checkpoint_age_secs
                        .map(|a| a.to_string())
                        .unwrap_or_else(|| "?".into()),
                );
            }
        }
        Err(error) => {
            let _ = writeln!(out, "failed to collect metrics: {error}");
        }
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## Resolved configuration");
    let _ = writeln!(out);
    match serde_yaml::to_string(&config.app) {
        Ok(yaml) => {
            let _ = writeln!(out, "```yaml");
            let _ = write!(out, "{yaml}");
            let _ = writeln!(out, "```");
        }
        Err(error) => {
            let _ = writeln!(out, "failed to serialize configuration: {error}");
        }
    }

    out
}

/// Write the bundle to `path`, or to a timestamped file in the working directory.
pub fn write(
    config: &RuntimeConfig,
    state: &Arc<AppState>,
    path: Option<PathBuf>,
) -> std::io::Result<PathBuf> {
    let path = path.unwrap_or_else(|| Path::new("piramid-support-bundle.md").to_path_buf());
    fs::write(&path, render(config, state))?;
    Ok(path)
}
